services:
  noip-renewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noip-renewer
    ports:
      - "7895:7895"
    volumes:
      - noip_data:/data
    restart: unless-stopped
    environment:
      - GITHUB_REPO=https://github.com/W00DFISH/noip-renewer-docker
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

volumes:
  noip_data:
