services:
  noip-renewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noip-renewer
    ports:
      - "7895:7895"
    volumes:
      - noip_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - GITHUB_REPO=https://github.com/W00DFISH/noip-renewer-docker
      - CONTAINER_NAME=noip-renewer
      - PORTAINER_WEBHOOK=${PORTAINER_WEBHOOK:-}  # Optional: Portainer stack webhook URL
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

volumes:
  noip_data:
